[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "topobathyserve"
version = "0.1.0"
description = "Microservice wrapping topobathykit"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic-settings",
  "fastapi-cache2[redis]",
  "click",
  "topobathykit @ file://../../topobathykit"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["topobathyserve"]

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "httpx"
]
